### ISSUE TITLE
Replace dependency on 'vscode.previewHtml'

### ISSUE THREAD

**Issue by johnknoop** [chaliy/vscode-handlebars-preview#10]
![image](https://user-images.githubusercontent.com/3394270/55489346-0e502e00-5632-11e9-84a1-040390defb9d.png)

**Comment by rohangeorge91** [comment]
Yeah +1 to this, since vscode dropped the command altogether from v1.33
[https://github.com/Microsoft/vscode/issues/62630#issuecomment-459898226](#62630)

**Comment by johnknoop** [comment]
I'm not sure of this project has been abandoned or not. Perhaps someone would care to fork it?

**Comment by labean365** [comment]
Another +1 to this — would love for this extension to be updated if possible, thx!

**Comment by johnknoop** [comment]
There is a fork of this repo that seems to work ok. Getting some weird output in the rendered preview, but at least it's mainained so hopefully they'll sort it out:

https://github.com/anonimitoraf/vscode-handlebars-preview

**Comment by johnknoop** [comment]
Note: the extension I linked to above doesn't seem very complete.

I took it upon myself to create a new one: https://github.com/johnknoop/vscode-handlebars-preview

It'll be published to Marketplace shortly.

**Comment by wamra** [comment]
You can't use this extension anymore :( 

![image](https://user-images.githubusercontent.com/3786934/59948856-6df2f400-943f-11e9-838f-c700533aa572.png)

**Comment by johnknoop** [comment]
> did anyone find a solution ?

@wamra See my reply above:

> I took it upon myself to create a new extension: https://github.com/johnknoop/vscode-handlebars-preview
> 
> It's not published to the marketplace yet, since I'll probably publish it under the name of the company I work for and we haven't sorted out everything yet, but in the meantime you can download the [VSIX package](https://github.com/johnknoop/vscode-handlebars-preview/blob/master/vsix/handlebars-preview-1.0.0-beta.1.vsix) and install it by opening the Extensions pane and choosing "Install from VSIX" under the ••• menu.

**Comment by rohangeorge91** [comment]
Thanks, John... I was having a hard time figuring out the old-code and how to convert to the new vs-code API...

**Comment by johnknoop** [comment]
Our new extension is now published:

https://marketplace.visualstudio.com/items?itemName=greenbyte.handlebars-preview

**Comment by SaebAmini** [comment]
Excellent! thanks @johnknoop.

**Comment by filetvignon** [comment]
@johnknoop just tried it and it looks great, thanks man! Really helping out a lot
