### ISSUE TITLE
Command 'Handlebars: Open Preview' resulted in an error

### ISSUE THREAD

**Issue by amaau** [chaliy/vscode-handlebars-preview#12]
Trying to run on an html-like hbs file results in this:

![image](https://user-images.githubusercontent.com/25984726/125979659-41a742c6-1d8b-4279-a6ff-d68c7e94d146.png)

Don't even know where to look for error information

**Comment by chef88val** [comment]
+1
![image](https://user-images.githubusercontent.com/7094117/143221294-909f74d0-9aa4-40a8-a8bd-00184729f88b.png)

**Comment by mohammadsadeghforoughi** [comment]
same issue

**Comment by chaliy** [comment]
Addressed with https://github.com/chaliy/vscode-handlebars-preview/commit/8c8c5edd47543e21c6d1127c48f0968cb1e5adeb

@amaau @regisfaria  @chef88val @mohammadsadeghforoughi it might be a little bit late (sorry for that), but extension got fixed.
