### ISSUE TITLE
Support *.handlebars.json

### ISSUE THREAD

**Issue by TimBailey-pnk** [chaliy/vscode-handlebars-preview#2]
I have a few handlebar files for email templates, each file has a part of the email, ie htmlbody, plaintextbody and subject.  This all live in the same folder, would be nice to have a single handlebars.json file that gets used for all files?

**Comment by chaliy** [comment]
Hello @TimBailey-pnk do you sill interested in this functionality? I am closing this issues for now, feel free to re-open it.
