### ISSUE TITLE
Multiple json files

### ISSUE THREAD

**Issue by neurospeech** [chaliy/vscode-handlebars-preview#6]
Most of the time we have conditional templates, where in same template looks different based on slight variations in input model. For example, invoice with Discount applied will have additional fields compared to simple invoice.

`invoice-template.handlebars`
with
`invoice-template.handlebars.success.json`
`invoice-template.handlebars.success-discount.json`

Also would it be possible to avoid handlebar extension and use pure `.html`

**Comment by chaliy** [comment]
Hello @neurospeech it is most likely too outdated response, but do you sill interested in this functionality? I am closing this issue for now, feel free to reopen.
